{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.yudady",
    "module": "utils",
    "version": "0.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-0.0.2-SNAPSHOT-plain.jar",
          "url": "utils-0.0.2-SNAPSHOT-plain.jar",
          "size": 25514,
          "sha512": "0dc9ed26f8ff6ed0989a21471d466648e2740ec8701eb32dfe26ffd748287f44fda57f72256955925548952479ea89a88eac11db001708a0034b5c4a838d12bc",
          "sha256": "df570824c46b84c1a102eafe4dba41df219b609d4bd7320b62f3e4411acd5967",
          "sha1": "57e6717047b7fb207cacea52da319b0d1b11db2d",
          "md5": "2918fd474cd1aed68b664df74c7c1d01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis"
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.2-SNAPSHOT-plain.jar",
          "url": "utils-0.0.2-SNAPSHOT-plain.jar",
          "size": 25514,
          "sha512": "0dc9ed26f8ff6ed0989a21471d466648e2740ec8701eb32dfe26ffd748287f44fda57f72256955925548952479ea89a88eac11db001708a0034b5c4a838d12bc",
          "sha256": "df570824c46b84c1a102eafe4dba41df219b609d4bd7320b62f3e4411acd5967",
          "sha1": "57e6717047b7fb207cacea52da319b0d1b11db2d",
          "md5": "2918fd474cd1aed68b664df74c7c1d01"
        }
      ]
    }
  ]
}
