{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.yudady",
    "module": "tools-utils",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tools-utils-0.0.1-SNAPSHOT-plain.jar",
          "url": "tools-utils-0.0.1-SNAPSHOT-plain.jar",
          "size": 23772,
          "sha512": "64e4d0fa97968e9dc9a2bbb2f7f288b57a52fe8483b2bf0a86fa0299948d321c1015ab1d354337d774de819eeabf31f2deab6224ff7f0e09122db7b9ff6909ac",
          "sha256": "dffadb71c6fb63a67645ff1f903361b3aae068b632d6f65d2e6171be313a2d5c",
          "sha1": "ca60540076b7875b9486e2037858e902e9a1ca33",
          "md5": "f66fd888634f0721e6e5db25e4071352"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "tools-utils-0.0.1-SNAPSHOT-plain.jar",
          "url": "tools-utils-0.0.1-SNAPSHOT-plain.jar",
          "size": 23772,
          "sha512": "64e4d0fa97968e9dc9a2bbb2f7f288b57a52fe8483b2bf0a86fa0299948d321c1015ab1d354337d774de819eeabf31f2deab6224ff7f0e09122db7b9ff6909ac",
          "sha256": "dffadb71c6fb63a67645ff1f903361b3aae068b632d6f65d2e6171be313a2d5c",
          "sha1": "ca60540076b7875b9486e2037858e902e9a1ca33",
          "md5": "f66fd888634f0721e6e5db25e4071352"
        }
      ]
    }
  ]
}
