{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.yudady",
    "module": "utils",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-0.0.1-SNAPSHOT-plain.jar",
          "url": "utils-0.0.1-SNAPSHOT-plain.jar",
          "size": 23772,
          "sha512": "855ddc6a978414b9fd55cad74a5ff846db007f8af646ee30373f052209c92b09926a4f69c390199877df2f26aa3304d273acc17c515985458423aad242799685",
          "sha256": "267e612f4bc27b4eadcd6373fcfe3a720f9864afc7e3b89be367c5101ea9c85a",
          "sha1": "57063265332d2994daed83fe478c7792d927749a",
          "md5": "c0475eec7d20b8712c5041546f3aa3ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.1-SNAPSHOT-plain.jar",
          "url": "utils-0.0.1-SNAPSHOT-plain.jar",
          "size": 23772,
          "sha512": "855ddc6a978414b9fd55cad74a5ff846db007f8af646ee30373f052209c92b09926a4f69c390199877df2f26aa3304d273acc17c515985458423aad242799685",
          "sha256": "267e612f4bc27b4eadcd6373fcfe3a720f9864afc7e3b89be367c5101ea9c85a",
          "sha1": "57063265332d2994daed83fe478c7792d927749a",
          "md5": "c0475eec7d20b8712c5041546f3aa3ea"
        }
      ]
    }
  ]
}
