{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.yudady",
    "module": "utils",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-0.0.1-SNAPSHOT-plain.jar",
          "url": "utils-0.0.1-SNAPSHOT-plain.jar",
          "size": 25019,
          "sha512": "6c5384b877042d5837f66132066846cb9701c4299034ee4750b635c96bb10b6b50387f371db89e3b1ba774fb765458a14a544b54afded9ecfbb7ddc1c9c044c2",
          "sha256": "2ceeb7df0d69b4d5db9995fce0256a11b67b5e84e574dd37f816ec137c0c96ab",
          "sha1": "2edd181146008006d154ab67d3252095e511248a",
          "md5": "51d369ba5414cb943ac02d5c086c7f1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.1-SNAPSHOT-plain.jar",
          "url": "utils-0.0.1-SNAPSHOT-plain.jar",
          "size": 25019,
          "sha512": "6c5384b877042d5837f66132066846cb9701c4299034ee4750b635c96bb10b6b50387f371db89e3b1ba774fb765458a14a544b54afded9ecfbb7ddc1c9c044c2",
          "sha256": "2ceeb7df0d69b4d5db9995fce0256a11b67b5e84e574dd37f816ec137c0c96ab",
          "sha1": "2edd181146008006d154ab67d3252095e511248a",
          "md5": "51d369ba5414cb943ac02d5c086c7f1b"
        }
      ]
    }
  ]
}
