{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.yudady",
    "module": "utils",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-0.0.1-SNAPSHOT-plain.jar",
          "url": "utils-0.0.1-SNAPSHOT-plain.jar",
          "size": 25019,
          "sha512": "36632825487c44e2667b6829b620fc865f413c6859e91ac76aa6b09be1359052a9339e9f54dc262e07bbcc50ff7aa67e930bc768376714d7e0a2bf441f34aa7e",
          "sha256": "26a175538974946ea355113a2528f7c08bcb6abc079b5fb361d6078650f7fd8d",
          "sha1": "a3f19fdf002b50000ee9de504d2260c69ddf1366",
          "md5": "2c181972d6d5354c6f6abc6b4538ab0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.1-SNAPSHOT-plain.jar",
          "url": "utils-0.0.1-SNAPSHOT-plain.jar",
          "size": 25019,
          "sha512": "36632825487c44e2667b6829b620fc865f413c6859e91ac76aa6b09be1359052a9339e9f54dc262e07bbcc50ff7aa67e930bc768376714d7e0a2bf441f34aa7e",
          "sha256": "26a175538974946ea355113a2528f7c08bcb6abc079b5fb361d6078650f7fd8d",
          "sha1": "a3f19fdf002b50000ee9de504d2260c69ddf1366",
          "md5": "2c181972d6d5354c6f6abc6b4538ab0e"
        }
      ]
    }
  ]
}
