{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.yudady",
    "module": "utils",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-0.0.1-SNAPSHOT-plain.jar",
          "url": "utils-0.0.1-SNAPSHOT-plain.jar",
          "size": 25019,
          "sha512": "65bb73ea44058cfa9bdad2feae5419d2780928b4d648a2afa14c1a10d871092c827edd68e0d4fa5c4bf7ba2ff4c9d0b07481070a2c6420bc082da03b1d848c78",
          "sha256": "a056935c1365da1299e3cc77147e4be1229c21fb2f32873a9ebd131bfb59e2b6",
          "sha1": "978984247b8f41021df2553c37d8c93c13ff1fd6",
          "md5": "cef929c7b46592306cda57afdb4e05c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.1-SNAPSHOT-plain.jar",
          "url": "utils-0.0.1-SNAPSHOT-plain.jar",
          "size": 25019,
          "sha512": "65bb73ea44058cfa9bdad2feae5419d2780928b4d648a2afa14c1a10d871092c827edd68e0d4fa5c4bf7ba2ff4c9d0b07481070a2c6420bc082da03b1d848c78",
          "sha256": "a056935c1365da1299e3cc77147e4be1229c21fb2f32873a9ebd131bfb59e2b6",
          "sha1": "978984247b8f41021df2553c37d8c93c13ff1fd6",
          "md5": "cef929c7b46592306cda57afdb4e05c9"
        }
      ]
    }
  ]
}
